export const homeObjOne = {
    lightBg: false,
    primary: true,  
    imgStart: '',
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: 'Get Started',
    description: 'If you need someone to help you plan your finances or advise on the best investment vehicle for your hard-earned finances, then look no further. At Stock Market Advisory we can help with independent advice for tax efficient financial planning, investment management and business development. We are located in the local area. To find out more about how we can help you develop a sound financial strategy, contact us through our booking form today.',
    headline: 'Top Financial Advisor in the local area',
    lightText: true,
    topLine: 'Ecotrics Financials',
    start:'',
    img: require('../../assets/stockProfit2.svg'),
    alt:'Stock Photo of Stock Profit',
}

export const homeObjTwo = {
    lightBg: true,
    primary: true,  
    imgStart: 'start',
    lightTopLine: false,
    lightTextDesc: false,
    buttonLabel: 'Get Started',
    description: 'ECOTRICS Is An Indian Stock Market Trading advisory firm based  in Bangalore To diversify Trading Financial Services In India. A Trading Style,Technical Analysis and Technical Tables Chart Of Your First Trade. ECOTRICS The Trading Platform For Liking It So That You Can Get Understood The Various Modifications Of Trading Financial Investments All Over India. Our 9+ Years of experience, Technology-driven quality research, Easy to follow signals and Proven track record made us the top investment advisory. ECOTRICS aims to change the perception of Trading in people’s minds. We want to establish that Responsible Trading is always rewarding experience.We provide our entrepreneurs, strategic shareholders and venture capital clients with independent advice, empowering them to make informed decisions at all points in the listing process. ',
    headline: 'Good reviews and recommendations',
    lightText: false,
    topLine: 'Ecotrics Financials',
    start:'true',
    img: require('../../assets/stockProfit.svg'),
    alt:'Stock Photo of Stock Profit',
}

export const homeObjThree = {
    lightBg: false,
    primary: true,  
    imgStart: '',
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: 'Get Started',
    description: 'We have a single task, and that task is to provide you with the most optimal solutions to your financial questions. With this in mind, we are committed to giving you the right advice in all financial matters. Given our expertise in financial management, we are committed to helping you achieve your goals in both the short and long term. We want to be your number one financial advisor, so why not get in touch and see how we can help you realise your financial goals?',
    headline: 'Your Goals are our Goals',
    lightText: true,
    topLine: 'Ecotrics Financials',
    start:'',
    img: require('../../assets/stockGrow.svg'),
    alt:'Stock Photo of Stock Profit',
}
